language: perl
perl:
  - "5.26"
  - "5.20"
  - "5.10"
env:
  - "HARNESS_OPTIONS=j9"
install:
  - "cpanm -n Test::Pod Test::Pod::Coverage IO::Socket::SSL"
  - "cpanm -n --installdeps ."
notifications:
  email: false
